name: request
type: json

server:
  url: http://localhost:8000/
  routes:
    data: query
    file: csv

# carpeta con la queries
queries_path: '/conexion_db/sql/'
# Otras carpetas
downloads: './downloads/data.csv'

query_prueba: prueba.sql