name: request
type: json

DB_server:
  url: <aqui va la url y el puerto del servidor de basisi de datos>
  routes:
    data: query
    file: csv

# carpeta con la queries
queries_path: '/queries_db/sql/'
# Otras carpetas
downloads: 'data.csv'

query_prueba: prueba.sql